include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_return: warning
    todo: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated_plugin_registrant.dart"
    
linter:
  rules:
    use_key_in_widget_constructors: false
