name: maily
description: A new Flutter project.
publish_to: "none"
version: 0.0.1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^4.2.7
  freezed_annotation: ^2.1.0
  flutter_riverpod: ^1.0.4
  intl: ^0.17.0
  enough_mail: ^2.1.1
  shared_preferences: ^2.0.15
  built_collection: ^5.1.1
  flutter_secure_storage: ^5.1.0
  http: ^0.13.5
  logging: ^1.0.2
  jwt_decoder: ^2.0.1
  webview_flutter: ^3.0.4
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.1.0+1
  mocktail: ^0.3.0

  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
